import Head from 'next/head';
import Image from 'next/image';
import Hero from '../components/Hero';
import Instagram from '../components/Instagram';
import Slider from '../components/Slider';
import { SliderData } from '../components/SliderData';
import Mission from "../components/Mission";
import About from "../components/About";
import Services from "../components/Services";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Felix Woodwork</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Hero heading='Felix Woodworking' message='Craftsmanship You Can Trust - Quality Carpentry from Our Family to Yours.' />
      <About />
      <Mission />
      <Services />
      {/*<Slider slides={SliderData} />*/}
      {/*<Instagram />*/}
    </div>
  );
}
